### ISSUE TITLE
Improve blocks read author contents by readBlockMarkup method

### ISSUE THREAD

**Issue by JiangLong2019** [aemsites/icicidirect#164]

**Comment by anagarwa** [comment]
@JiangLong2019 anything pending on this one ?

**Comment by JiangLong2019** [comment]
@anagarwa It came from this conversation.
https://github.com/aemsites/icicidirect/pull/160#discussion_r1565149586

**Comment by anagarwa** [comment]
@JiangLong2019  In present , I cannot see possibility any use of `readBlockMarkup` apart from here. https://github.com/aemsites/icicidirect/blob/main/blocks/faq/faq.js#L86. But since this is where we are iterating the whole block already so this seems to be a safe use. 
If you agree, we can go ahead and close the issue.

**Comment by JiangLong2019** [comment]
@anagarwa Agree. If we get any request from customer, we can use readBlockMarkup across blocks. Close this ticket for now.
