### ISSUE TITLE
Recent Reports & Rapid Results Next to each other

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#179]
<img width="252" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/d33b7948-5164-46f5-b005-ec312f3840e4">
<img width="840" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/112b3afd-9802-4303-9f28-15bdf3d1bf17">

More Details 
[More details](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/icicidirect/internal/AEM%20-%20Business%20Team%20Requirement_final.xlsx?d=w9f5f55c7a7b6492684c6128abc11816d&csf=1&web=1&e=IoQkfK)

**Comment by JiangLong2019** [comment]
Shall we just move the 2 blocks next to each other? If we need to implement below `Suggested Functionality`, the description is not clear enough for development, we need to get more details and sample markup.

```
Section:
1. Dynamically hide if there is no Recent results, should have an option to write content dynamically.
2. Should be able to display the IPOs in tiles/card listicle format

3. Ability to add/ remove the tiles/ cards lock to any or all as per our requirements.
4.Furthermore, require functionality where we can add/ change/ remove promotional images or scannable OR codes over locked tiles/ cards. whenever required.
4..a) Essentially the system should have the capability to pick up an image and increase transparency of the image and get used as a lock.
```

**Comment by JiangLong2019** [comment]
**Implementation plan:**
A. keep rapid-result & recent-report as separate block, use `layout-60-40` to create side by side layout.
B. Combine rapid-result & recent-report as one block.

**Pros&cons**
Plan A    | Plan B
------------- | -------------
Reuse existed blocks with limit refactoring | Easy to control the order of API calls, hide blocks would have a good experience
The block can be used separated when user needs | Much effort on refactoring
Need to take care of hide blocks when each API doesn't return result | Need to consider authoring experience carefully because it includes two blocks configuration

Obviously, plan A has good experience in authoring, provides more options, and is easier to implement, we will start from Plan A.

I've refactored rapid-result with following changes in branch `rapidresult-recentreport-draft` and test page is https://rapidresult-recentreport-draft--icicidirect--aemsites.hlx.page/draft/jiang/rapidresult-recentreport
1. Made a variation of rapid-result(`side by side`) for the side by side layout.
2. Hide block itself when there is no data return back from API.
3. Support QR code image. Author can use `Cover image` to configure QR image and `Number of cover image` to control the number of cards that show the image. 

**Next action**
1. Refactor recent-report to support the same as above changes.
2. Confirm with the customer which block needs to show IPO data and where the data comes from. 
3. rapid-result is using mock data, will integrate API when we receive it.
4. About hide block, I realize that the section has a padding button. To make a good experience, an idea is that move the padding to each block so that there is nothing to be shown when blocks are hided. This requires changes both blocks. Just an idea

**Comment by anagarwa** [comment]
Not considering the current phase. Closing this one.  let feature branch have the changes for now.
